### ISSUE TITLE
Animation during loading

### ISSUE THREAD

**Issue by pommedeterresautee** [DHuckaby/Prime#10]
Hi,

Thank you for your Library.
Is it possible that you add a loader animation during the downloading of the image?

Thanks

**Comment by DHuckaby** [comment]
What type of animation? This would not be included in the standard RemoteImageView but a subclass of it with animation support could defiantly be an option. I have played with this idea in the past but I thought it more of an implementation detail than of an image loading, which RemoteImageView is specifically for.

**Comment by pommedeterresautee** [comment]
I think a ProgressBar, or any other ImaveView we want...
In UrlImageViewHelper, that's how Kouch has done... but I understand your point of view!

**Comment by DHuckaby** [comment]
You can set whatever image you want as a default, via the normal ImageView methods which are inherited into the RemoteImageView. Having specifically a spinner will only work if implemented correctly, for example if you incorrectly implement it within a recycling adapter I will be unable to correctly display the spinner.

Since the RemoteImageView is only a custom ImageView I would have to create an internal spinner, not use a ProgressBar.

**Comment by pommedeterresautee** [comment]
What do you mean by spinner ? For me it s just a kind of option menu...

For the moment I have instantiate in java a framelayout, inside a linear layout with the progress bar and on top the image view. May be you can do something like that inside the lib so you can use whatever you want... In the constructor of remote image you would ask for the loading animation and the image view ... It s just an idea!

**Comment by DHuckaby** [comment]
The RemoteImageView is an actual ImageView itself so nesting Views within it is not an option. If I wanted to have a progress spinner I would have to use a RotateDrawable to fake a ProgressBar. I will keep it as an active issue for a later release.

**Comment by RobGThai** [comment]
Would accompanying ProgressBar into every RemoteImageView be expensive?

**Comment by DHuckaby** [comment]
It is not possible it add a ProgressBar to a RemoteImageView because it is an ImageView, thus not a ViewGroup.

**Comment by DHuckaby** [comment]
If you want to jump onto the loading-imageview branch and switch all of your RemoteImageView references to LoadingImageView you can test it. It currently is pretty basic, the progress spinner is just the background. If you have any other behavior you would like it to have please suggest it because I won't personally be using this widget.

**Comment by DHuckaby** [comment]
This will be rolled into the next release candidate but will be an undocumented api because I do not suggest users becoming reliant on my implementation.
